### ISSUE TITLE
Конфиг update addon из примера пишет ошибку и не стартует

### ISSUE THREAD

**Issue by lupin-de-mid** [andvikt/mega_addon#5]
установил версию 0.3.2 
Попробовал скопировтаь конфиг из документации
```localip: 192.168.0.37  # ip адрес вашего home-assistant
hosts:
  - ip: 192.168.0.14  # ip адрес megad
    password: sec
  # их можно указать несколько:
  - ip: 192.168.0.15
    password: sec
```

При вставке он отформатировался до 

```
localip: 192.168.0.37
hosts:
  - ip: 192.168.0.14
    password: sec
  - ip: 192.168.0.15
    password: sec
``` 

в логе `[FATAL tini (7)] exec docker-php-entrypoint failed: Exec format error`

 Попробовал простой конфиг

```
localip: 192.168.0.37
hosts:
  - ip: 192.168.0.14
    password: sec
```
Результат тот же
